### ISSUE TITLE
Attribute Error While Running

### ISSUE THREAD

**Issue by Gokulakannanaj** [SantiagoEG/FCBF_module#1]
The error is below:

Traceback (most recent call last):
  File "test.py", line 24, in <module>
    n_features = dataset.shape[1]
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/__init__.py", line 73, in __getattr__
    raise AttributeError(key)
AttributeError: shape

**Comment by SantiagoEG** [comment]
Hi Gokulakrishnan,

Is the error still happening?
Note that the line in the most recent version of test.py is:
n_features = dataset.data.shape[1]

and not:
n_features = dataset.shape[1]

I hope this help you.
Best

**Comment by Gokulakannanaj** [comment]
Thank You so much @SantiagoEG.
Inside of the suGroup method i get an TypeError: reshape() takes at least 2 arguments (1 given).
i change the code like x = np.reshape(x, (n,m//n)).T is it correct ?

Another one - Is it possible to read data like csv file ? If it's possible just give that format.

**Comment by SantiagoEG** [comment]
Check if you have the last version of the FCBF_module, because that's the
same is written in my code.
I show you the suGroup function:


def suGroup(x, n):
m = x.shape[0]
x = np.reshape(x, (n,m/n)).T
m = x.shape[1]
SU_matrix = np.zeros(shape = (m,m))
for j in range(m-1):
x2 = x[:,j+1::]
y = x[:,j]
temp = np.apply_along_axis(symmetricalUncertain, 0, x2, y)
for k in range(temp.shape[0]):
SU_matrix[j,j+1::] = temp
SU_matrix[j+1::,j] = temp
return 1/float(m-1)*np.sum(SU_matrix, axis = 1)

Best,
Santiago

**Comment by Gokulakannanaj** [comment]
I changed it. 
Now i want to load dataset from Excel or CSV file. What is the data format i directly print the dataset but if it contains the values inside of the dictionary. Can you show me data format for CSV or Excel file ?

**Comment by SantiagoEG** [comment]
Read to load CSV with pandas:
https://chrisalbon.com/python/data_wrangling/pandas_dataframe_importing_csv/

After loading the dataset, you must map categorical values to numerical.
And transform the dataset to numpy array:
array = np.array(dataset)

Saludos
Santiago

**Comment by Gokulakannanaj** [comment]
I'll check and update soon

**Comment by Gokulakannanaj** [comment]
Hi !! I attached my test.csv file while trying to run this file, i'm getting IndexError: tuple index out of range.
I don't know whats  wrong with the CSV file .

![screenshot from 2018-10-24 00-07-40](https://user-images.githubusercontent.com/41570711/47382896-04401000-d721-11e8-956b-1964b72cefb2.png)
![samples](https://user-images.githubusercontent.com/41570711/47382999-479a7e80-d721-11e8-9b78-a657eeef30f5.png)

When i run the below file(screenshot attached) i'm getting below error

/usr/local/lib/python2.7/dist-packages/sklearn/utils/fixes.py:313: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  _nan_object_mask = _nan_object_array != _nan_object_array
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    n_features = dataset.data.shape[1]
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'data'

![screenshot from 2018-10-24 00-40-28](https://user-images.githubusercontent.com/41570711/47384706-a7932400-d725-11e8-9141-86b27dd5dcdc.png)

**Comment by Gokulakannanaj** [comment]
How can i convert load_digits() to CSV file ?
What is the CSV format for load_digits. When i trying to insert above lung cancer dataset i'm getting AttributeError: 'DataFrame' object has no attribute 'data'

And my code is below.

dataset=pd.read_csv("/home/Downloads/lungcancer.csv")
#dataset = load_digits()
n_features = dataset.data.shape[1]

**Comment by SantiagoEG** [comment]
Hi,

note that in your lungcancer.csv there are empty values. You should read
the documentation about how to manage csv files with pandas:
https://chrisalbon.com/python/data_wrangling/pandas_dataframe_importing_csv/


Try to write your own code and do nor replace directly in the mine. My code
is only an example.

**Comment by Gokulakannanaj** [comment]
Hi,
see Picture (screenshot 1 and 2), when i trying to use that file i;m getting the IndexError: tuple index out of range.

Can you provide CSV or excel format for load_digits()

**Comment by SantiagoEG** [comment]
I do not know why the error is happening.
Sorry.

**Comment by Gokulakannanaj** [comment]
Can you provide csv or excel format for load_digits()

**Comment by SantiagoEG** [comment]
You can get it from this link:
https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/datasets/data/digits.csv.gz

**Comment by NadaMugren** [comment]
hi 
when I run the FCBC model, the model select one feature only (I run it od dataset with 2000 features)? 
is there a way to specify the number of selected features?
thanks

**Comment by SantiagoEG** [comment]
Hi,

as you can note from the description of FCBF, this algorithm performs a
preselection phase in which the features that do not overcome a threshold
in terms of symmetrical uncertainty are directly excluded from the
subsequent selection step. So, your attributes are being removed in this
phase and none of them reach the following step. Note that the threshold is
fixed as 0.01 by default: def __init__(self, th = 0.01).
Try with other thresholds when you initialize the algorithm, example: fcbf =
FCBF(th = 0.001).

Good luck!

**Comment by SantiagoEG** [comment]
Regarding your other inquiry. Note that the preliminary preselection phase
does not enable to select the number of selected features in my
implementation.
FCBF outputs a final subset. When I have more free time I'll to reimplement
it. Sorry for inconvinences.
Regards

**Comment by Gokulakannanaj** [comment]
Thanks.
